all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
all_joints_names:
- Head
- HeadAttach
- RightFin
- LeftFin
- TailAttach
- TailTip
batch_size: 8
cropratio: 0.4
dataset: training-datasets\iteration-0\UnaugmentedDataSet_GroupBehavior_0Oct10\GroupBehavior_0_PerksLab95shuffle1.pickle
dataset_type: multi-animal-imgaug
display_iters: 500
global_scale: 0.8
init_weights: C:\Users\kperks\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
max_input_size: 1500
metadataset: training-datasets\iteration-0\UnaugmentedDataSet_GroupBehavior_0Oct10\Documentation_data-GroupBehavior_0_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_step:
- - 0.0001
  - 7500
- - 5.0e-05
  - 12000
- - 1.0e-05
  - 200000
net_type: resnet_50
num_joints: 6
num_limbs: 14
optimizer: adam
pafwidth: 20
pairwise_huber_loss: false
pairwise_loss_weight: 0.1
pairwise_predict: false
partaffinityfield_graph:
- - 0
  - 1
- - 1
  - 2
- - 1
  - 3
- - 4
  - 5
- - 1
  - 4
- - 2
  - 5
- - 0
  - 5
- - 0
  - 4
- - 2
  - 3
- - 2
  - 4
- - 0
  - 3
- - 3
  - 4
- - 0
  - 2
- - 3
  - 5
partaffinityfield_predict: true
pos_dist_thresh: 17
project_path: D:\DLC\GroupBehavior_0-PerksLab-2020-10-10
rotation: 25
rotratio: 0.4
save_iters: 10000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
weigh_only_present_joints: false
